### ISSUE TITLE
Support for Eigen::Block<> ?

### ISSUE THREAD

**Issue by luca-penasa** [eudoxos/minieigen#12]
Any idea to extend miniegen to support eigen blocks? I am wrapping some methods that returns blocks, thus I was wondering if a Block wrapper could be difficult to implement.. (?) or if maybe there could be some simple workaround within eigen itself...

cheers
luca

**Comment by eudoxos** [comment]
Depends on what block operations are needed and if they copy data or refer the old ones.

Returning copies is much easier (the downside is that even if you modify the copy, the original will not change, so block assignments will not work). If you look at https://github.com/eudoxos/minieigen/blob/master/src/visitors.hpp#L292 you see how is `row` and `col` implemented, so a similar method `block` would be created, with 4 arguments (upper left corner, and size of the block). The question would also be if block returns fixed-size matrices or dynamic ones (of the same size, but technically they are a different type), if 1x1 block is scalar or 1x1 matrix, and such things. I try to stay close to Eigen API as much as possible, but it is not always possible. 

Returning references to the other data gets much more complicated, because it is a different type (not owning its own data) and the whole expression machinery would have to be re-implemented in the wrapper (such as that 3x1 block can be added to 3x1 vector and so on); maybe adding automatic conversions from block to the copy (which would effectively copy the data on-demand) would be something to look at.

If you only want to have the method's results converted, registering a to-python converter for blocks might be enough. That would go presumably to src/converters, but the converter would have to be instantiated and registered for every block type you use (fixed-size plus dynamic sizes).

If you feel like it, go ahead and fork minieigen; we can check together how to tackle it.
